# -*- coding: utf-8 -*-
"""DNA to mRNA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zt7rW4pZ4yJ4muvw0p4zRD0YgiJDiodI

Install library
"""

!pip install biopython

"""fetch DNA + convert to mRNA"""

from Bio import Entrez, SeqIO
from Bio.Seq import Seq

Entrez.email = "hamzasandhu2353@email.com"   # put your email here

handle = Entrez.efetch(
    db="nucleotide", id="NM_000546",
    rettype="gb", retmode="text"
)
record = SeqIO.read(handle, "genbank")
handle.close()

dna_seq  = record.seq
mrna_seq = dna_seq.transcribe()

print("DNA  (first 60):", dna_seq[:60])
print("mRNA (first 60):", mrna_seq[:60])
print("mRNA length:", len(mrna_seq), "nucleotides")

# Save files
with open("TP53_DNA.fasta","w") as f:
    f.write(">TP53_DNA\n" + str(dna_seq) + "\n")
with open("TP53_mRNA.fasta","w") as f:
    f.write(">TP53_mRNA\n" + str(mrna_seq) + "\n")
    # Get protein too
for feat in record.features:
    if feat.type == "CDS":
        protein = feat.extract(record.seq).translate(to_stop=True)
        with open("TP53_protein.fasta","w") as f:
            f.write(">TP53_protein\n" + str(protein) + "\n")
        print("Protein length:", len(protein), "amino acids")
        break

print("Done! 3 files saved.")

"""Download the files"""

from google.colab import files
files.download("TP53_DNA.fasta")
files.download("TP53_mRNA.fasta")
files.download("TP53_protein.fasta")