# -*- coding: utf-8 -*-
"""GNINA Docking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifGJxpbfXYMie9e_3NMQyxWPqnPLWHvc

INSTALL GNINA & Download Ligand
"""

# Install GNINA
!wget -q https://github.com/gnina/gnina/releases/download/v1.0.3/gnina -O gnina
!chmod +x gnina

# Download ligand APR-246 from PubChem
import urllib.request
urllib.request.urlretrieve(
    "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/5713517/SDF",
    "APR246.sdf"
)
print("Ligand downloaded!")

"""PROTEIN PREPRATION"""

from google.colab import files

# Upload your AlphaFold .pdb file
uploaded = files.upload()   # select your .pdb file
pdb_name = list(uploaded.keys())[0]

# Clean protein (remove waters)
with open(pdb_name) as f_in, open("protein.pdb","w") as f_out:
    for line in f_in:
        if line.startswith("ATOM") and "HOH" not in line:
            f_out.write(line)
print("Protein ready!")

"""RUN DOCKING

"""

!./gnina \
  --receptor protein.pdb \
  --ligand APR246.sdf \
  --out docked_poses.sdf \
  --center_x 1.5 --center_y 2.3 --center_z -0.8 \
  --size_x 25 --size_y 25 --size_z 25 \
  --num_modes 9 \
  --exhaustiveness 8 \
  --cnn_scoring rescore

from google.colab import files
files.download("docked_poses.sdf")